algoritmo "procedimento"
// Função :
// Autor :
// Data : 19/05/2021
// Seção de Declarações 
var
   x, y: inteiro
procedimento Soma (var a, b:inteiro)
inicio
      a<-a+1
      b<-b+2
      escreval("valor de a = ",a)
      escreval("valor de b = ",b)
      escreval("valor de a+b = ",a+b)
fimprocedimento
inicio
// Seção de Comandos 
   x<-4
   y<-8
   soma (x, y)
   escreval("valor de x = ",x)
   escreval("valor de y = ",y)

fimalgoritmo
